# Generated by Django 5.2.7 on 2025-12-01 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('1', 'Electronic'), ('2', 'Furniture'), ('3', 'vechicle')], default=None)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Used', 'Used')], default='Good')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
