# Generated by Django 5.2.8 on 2025-12-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_itemsforsale_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsforsale',
            name='category',
            field=models.CharField(choices=[('1', 'Electronic'), ('2', 'Furniture'), ('3', 'vechicle')], default='none'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media.png', upload_to='media')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.itemsforsale')),
            ],
        ),
    ]
