# Generated by Django 5.2.8 on 2025-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_itemsforsale_category_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsforsale',
            name='image',
            field=models.ImageField(default='media.png', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='itemsforsale',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
